### ISSUE TITLE
data assignment needed

### ISSUE THREAD

**Issue by mars-s** [ScriptedRain/weather-app#2]
the issue is in dev branch in WeatherSearch.jsx 
we need a function something like useState where once the API has searched for the city it will receive a json and assign some targets from that json into a local var and display it on screen
![image](https://user-images.githubusercontent.com/71009876/125187209-cd640c80-e271-11eb-8f41-b7d807f24dd0.png)
as of right now the implementation is this
I was thinking to use something like this 
![image](https://user-images.githubusercontent.com/71009876/125187232-e076dc80-e271-11eb-8b03-1c7acd4ea6c8.png)
the app also has a problem with checking for data while the city is not selected so we need to use useState there as well.

**Comment by krishp058** [comment]
Fixed this issue by changing `const` to `let` at line 184
